### ISSUE TITLE
Unable to install kmod-macvlan and other packages

### ISSUE THREAD

**Issue by eloo** [pesa1234/MT6000_cust_build#1]
Hi,

i'm testing your build right now and have seen that with the latest version i'm not able to install kmod-macvlan.

this the error i'm facing:

```
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ipt-physdev found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.79-1-4a3c1cd3a4e65473dcdef01a32cbb597) for kmod-nf-ipvs
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-ipvs found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 6.1.79-1-4a3c1cd3a4e65473dcdef01a32cbb597) for kmod-veth

 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-macvlan found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-macvlan.

```

any ideas?

**Comment by forzic** [comment]
Non sono io l'autore della build

Il lun 26 feb 2024, 17:56 Joseph Weigl ***@***.***> ha
scritto:

**Comment by pesa1234** [comment]
Hi, I have added some kmod... https://github.com/pesa1234/MT6000_cust_build/tree/main/20240226_r25325_6.1.79/targets/mediatek/filogic/packages

Transfer via SCP to tmp and install `opkg install /tmp/*.ipk` the dependency that are listed...

Or tell me which package you need to install...
