### ISSUE TITLE
please update build to support apk installations....

### ISSUE THREAD

**Issue by jagga99** [pesa1234/MT6000_cust_build#10]
please update build to support apk installations....

**Comment by IamRPDev** [comment]
Related to being unable to update from https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/ and it various sub folders? I suspect openwrt switched their snapshot packages over to apk completely and no longer support opkg. This was driving me crazy until I realized what happed, I remembered reading about it the other day. I wanted to clarify that this is only for their snapshots as of right now.

**Comment by pesa1234** [comment]
Done
https://github.com/pesa1234/MT6000_cust_build/tree/main/2024-11-21_r28320-e01af5e8d6_next-r4.4.0.mtk
