### ISSUE TITLE
Please add kmod-ip6tunnel kmod-sit for tunneling

### ISSUE THREAD

**Issue by cmspam** [pesa1234/MT6000_cust_build#11]
Hello!
I have (as does most everyone else in Japan and parts of Europe) a connection which tunnels ipv4 over ipv6.

There is also the inverse situation of tunneling v6 through v4, which many people need as well, I think.

I added openwrt repositories to try to get the necessary software to do the tunneling I need, but got errors about modules missing.

If it would be possible for you to add the below kernel modules in the next build, it would be a big help to me, and others in my situation.

kmod-ip6tunnel
kmod-sit

In case it helps, the plugins I need to use this functionality were:
ds-lite map 6in4

I think if we have the kmod, I can just use that from openwrt repository, but if you want to include them, of course it's great.

A big thanks!

**Comment by pesa1234** [comment]
Here...

it is still a testing version but you can install whatever you want.

https://github.com/pesa1234/MT6000_cust_build/tree/main/2024-11-21_r28320-e01af5e8d6_next-r4.4.0.mtk

**Comment by cmspam** [comment]
I want to give you a big thanks. I installed the latest version, everything is working perfectly.
