### ISSUE TITLE
Fetch Error When Updating Package List on Custom Firmware for GL.iNet 6000

### ISSUE THREAD

**Issue by AmirulAndalib** [pesa1234/MT6000_cust_build#12]
Hello,  

Thank you for creating your custom firmware for the GL.iNet 6000. I am currently using the build from the following repository: https://github.com/pesa1234/MT6000_cust_build/tree/main/2024-11-21_r28320-e01af5e8d6_next-r4.4.0.mtk. However, when I attempt to update the package list, I encounter a fetch error.  

Any assistance in resolving this issue would be greatly appreciated.  

Thank you!  

![image](https://github.com/user-attachments/assets/461fd1a9-aa91-4ddb-893c-2d948b1e4b38)

**Comment by pesa1234** [comment]
Sorry, where's the error?
That is the apk update output and id ok

**Comment by AmirulAndalib** [comment]
> Sorry, where's the error?

```
Errors
fetch https://raw.githubusercontent.com/pesa1234/MT6000_cust_build/refs/heads/main/2024-11-21_r28320-e01af5e8d6_next-r4.4.0.mtk/targets/mediatek/filogic/packages/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/base/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/luci/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/packages/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing/packages.adb
fetch https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony/packages.adb
```

**Comment by pesa1234** [comment]
Sorry, where's the error? That output of apk update is ok

**Comment by AmirulAndalib** [comment]
> Sorry, where's the error? That output of apk update is ok

Oh, I’m sorry about the confusion! I assumed there were actual errors because they were displayed in the errors tab. I hope you understand.

**Comment by pesa1234** [comment]
I'll try to open a pr on owrt to change description from Error to Output
