### ISSUE TITLE
Add package

### ISSUE THREAD

**Issue by FalenDemon** [pesa1234/MT6000_cust_build#2]
Hi! Thanks for your builds! Can you add sing-box package?

**Comment by pesa1234** [comment]
> Hi! Thanks for your builds! Can you add sing-box package?

Yes, as module?

**Comment by FalenDemon** [comment]
> > Hi! Thanks for your builds! Can you add sing-box package?
> 
> Yes, as module?

Yes, as not-build-in.

**Comment by pesa1234** [comment]
> > > Hi! Thanks for your builds! Can you add sing-box package?
> > 
> > 
> > Yes, as module?
> 
> Yes, as not-build-in.

Uploaded

**Comment by FalenDemon** [comment]
> > > > Hi! Thanks for your builds! Can you add sing-box package?
> > > 
> > > 
> > > Yes, as module?
> > 
> > 
> > Yes, as not-build-in.
> 
> Uploaded

Will try in next few days! Thank you!
