### ISSUE TITLE
Request for nfs-kernel-server

### ISSUE THREAD

**Issue by KeyserSoze1** [pesa1234/MT6000_cust_build#3]
Thanks for the great work on this!

Requesting nfs-kernel-server and nfs-kernel-server-utils if possible.  I believe these require a few dependencies that are probably not already included.

**Comment by pesa1234** [comment]
On next release.

Thanks

![immagine](https://github.com/pesa1234/MT6000_cust_build/assets/6216993/56efd526-26e1-43de-a82b-c3f90ef852f4)

**Comment by KeyserSoze1** [comment]
Works!  Just pointed my opkg distsfeeds.conf to your latest build folders and was able to install this w/o issue.
