### ISSUE TITLE
Request for bridger package

### ISSUE THREAD

**Issue by stachdude** [pesa1234/MT6000_cust_build#5]
Hi,

waiting for a device, just ordered one, but I see there is no bridger package which is needed for AP mode and WED. If there is a chance, please add it to the build.

Thanks

**Comment by stachdude** [comment]
Ok, builded my own image based on your repo, so I got it working - still I believe that bridger should be made available, so leaving this opened.

Btw, thanks for all the work! Your fork makes this router a beast.

**Comment by pesa1234** [comment]
What is the name of bridger package missing?

So do you mean that if I enable WED, the WiFi don't work on AP mode?

**Comment by pesa1234** [comment]
Inserted in new release 3.1.0.mtk.
