### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by jeff47** [pesa1234/MT6000_cust_build#7]
Hello,
Thanks for putting this together!  I would like to learn how to compile this locally.  I know it's beyond what you intended to provide here, but could you include the steps needed to compile it?

**Comment by pesa1234** [comment]
Dear you can read first post in forum here: https://forum.openwrt.org/t/mt6000-custom-build-with-luci-and-some-optimization-kernel-6-6-x/185241
